import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const vehiclesData = [
  {
    id: "V-001",
    name: "Mercedes Actros 2545",
    model: "Actros 2545",
    type: "Heavy Truck",
    regNumber: "KCA 441Z",
    maxCapacity: 25000,
    odometer: 142350,
    acquisitionCost: 4200000,
    purchaseDate: new Date("2021-03-15"),
    insuranceExpiry: new Date("2025-03-14"),
    status: "On Trip",
    fuelType: "Diesel",
  },
  {
    id: "V-002",
    name: "Isuzu FVR 134",
    model: "FVR 134",
    type: "Medium Truck",
    regNumber: "KCB 112A",
    maxCapacity: 8000,
    odometer: 87420,
    acquisitionCost: 1850000,
    purchaseDate: new Date("2022-07-20"),
    insuranceExpiry: new Date("2025-07-19"),
    status: "Available",
    fuelType: "Diesel",
  },
  {
    id: "V-003",
    name: "Toyota Hilux GD6",
    model: "Hilux GD6",
    type: "Pickup",
    regNumber: "KCC 778B",
    maxCapacity: 1000,
    odometer: 34200,
    acquisitionCost: 380000,
    purchaseDate: new Date("2023-01-10"),
    insuranceExpiry: new Date("2025-06-30"),
    status: "In Shop",
    fuelType: "Diesel",
  },
  {
    id: "V-004",
    name: "UD Trucks Quon",
    model: "Quon GW26",
    type: "Heavy Truck",
    regNumber: "KCD 234C",
    maxCapacity: 30000,
    odometer: 289100,
    acquisitionCost: 5100000,
    purchaseDate: new Date("2019-11-05"),
    insuranceExpiry: new Date("2024-11-04"),
    status: "On Trip",
    fuelType: "Diesel",
  },
  {
    id: "V-005",
    name: "Hino 700 Series",
    model: "700 FY",
    type: "Heavy Truck",
    regNumber: "KCE 567D",
    maxCapacity: 22000,
    odometer: 198750,
    acquisitionCost: 3750000,
    purchaseDate: new Date("2020-06-22"),
    insuranceExpiry: new Date("2025-06-21"),
    status: "Available",
    fuelType: "Diesel",
  },
  {
    id: "V-006",
    name: "Ford Transit Van",
    model: "Transit Custom",
    type: "Van",
    regNumber: "KCF 890E",
    maxCapacity: 1400,
    odometer: 56300,
    acquisitionCost: 280000,
    purchaseDate: new Date("2022-09-18"),
    insuranceExpiry: new Date("2025-09-17"),
    status: "Available",
    fuelType: "Petrol",
  },
  {
    id: "V-007",
    name: "Scania R450",
    model: "R450 LA",
    type: "Heavy Truck",
    regNumber: "KCG 123F",
    maxCapacity: 28000,
    odometer: 412000,
    acquisitionCost: 6200000,
    purchaseDate: new Date("2018-04-12"),
    insuranceExpiry: new Date("2024-04-11"),
    status: "Retired",
    fuelType: "Diesel",
  },
];

const driversData = [
  {
    id: "D-001",
    name: "James Mwangi",
    licenseNumber: "DL-2019-00123",
    licenseCategory: "Class GV",
    licenseExpiry: new Date("2026-04-15"),
    safetyScore: 94,
    status: "On Trip",
    experience: "7 yrs",
    phone: "+254 712 345678",
    tripsCount: 847,
    incidentsCount: 1,
    rating: 4.8,
    avatar: "JM",
  },
  {
    id: "D-002",
    name: "Sarah Ochieng",
    licenseNumber: "DL-2021-00456",
    licenseCategory: "Class C",
    licenseExpiry: new Date("2025-08-22"),
    safetyScore: 88,
    status: "Available",
    experience: "4 yrs",
    phone: "+254 723 456789",
    tripsCount: 412,
    incidentsCount: 0,
    rating: 4.9,
    avatar: "SO",
  },
  {
    id: "D-003",
    name: "Peter Kamau",
    licenseNumber: "DL-2018-00789",
    licenseCategory: "Class GV",
    licenseExpiry: new Date("2024-12-01"),
    safetyScore: 71,
    status: "On Trip",
    experience: "9 yrs",
    phone: "+254 734 567890",
    tripsCount: 1203,
    incidentsCount: 4,
    rating: 4.5,
    avatar: "PK",
  },
  {
    id: "D-004",
    name: "Grace Wanjiku",
    licenseNumber: "DL-2022-00321",
    licenseCategory: "Class B",
    licenseExpiry: new Date("2025-11-30"),
    safetyScore: 97,
    status: "Off Duty",
    experience: "2 yrs",
    phone: "+254 745 678901",
    tripsCount: 156,
    incidentsCount: 0,
    rating: 5.0,
    avatar: "GW",
  },
  {
    id: "D-005",
    name: "David Otieno",
    licenseNumber: "DL-2020-00654",
    licenseCategory: "Class C",
    licenseExpiry: new Date("2024-06-15"),
    safetyScore: 62,
    status: "Suspended",
    experience: "5 yrs",
    phone: "+254 756 789012",
    tripsCount: 634,
    incidentsCount: 7,
    rating: 3.9,
    avatar: "DO",
  },
  {
    id: "D-006",
    name: "Mary Njeri",
    licenseNumber: "DL-2021-00987",
    licenseCategory: "Class B",
    licenseExpiry: new Date("2026-02-28"),
    safetyScore: 91,
    status: "Available",
    experience: "3 yrs",
    phone: "+254 767 890123",
    tripsCount: 289,
    incidentsCount: 0,
    rating: 4.7,
    avatar: "MN",
  },
];

const tripsData = [
  {
    id: "T-001",
    tripId: "TR-8821",
    vehicleId: "V-001",
    driverId: "D-001",
    origin: "Nairobi CBD",
    destination: "Mombasa Port",
    status: "In Progress",
    eta: "18:30",
    distance: "480 km",
    cargo: "Electronics",
    weight: 18500,
    priority: "High",
  },
  {
    id: "T-002",
    tripId: "TR-8820",
    vehicleId: "V-004",
    driverId: "D-003",
    origin: "Eldoret ICD",
    destination: "Nairobi Westlands",
    status: "In Progress",
    eta: "16:45",
    distance: "310 km",
    cargo: "Agricultural Produce",
    weight: 27000,
    priority: "Normal",
  },
  {
    id: "T-003",
    tripId: "TR-8819",
    vehicleId: "V-002",
    driverId: "D-002",
    origin: "Nairobi CBD",
    destination: "Kisumu City",
    status: "Completed",
    eta: "—",
    distance: "340 km",
    cargo: "FMCG Goods",
    weight: 6200,
    priority: "Normal",
  },
  {
    id: "T-004",
    tripId: "TR-8818",
    vehicleId: "V-006",
    driverId: "D-006",
    origin: "Karen Estate",
    destination: "Wilson Airport",
    status: "Completed",
    eta: "—",
    distance: "12 km",
    cargo: "Documents",
    weight: 45,
    priority: "Urgent",
  },
  {
    id: "T-005",
    tripId: "TR-8817",
    vehicleId: "V-005",
    driverId: "D-004",
    origin: "Athi River EPZ",
    destination: "Thika Town",
    status: "Cancelled",
    eta: "—",
    distance: "52 km",
    cargo: "Industrial Parts",
    weight: 14000,
    priority: "Normal",
  },
  {
    id: "T-006",
    tripId: "TR-8816",
    vehicleId: "V-002",
    driverId: "D-002",
    origin: "Nairobi CBD",
    destination: "Nakuru City",
    status: "Scheduled",
    eta: "Tomorrow 08:00",
    distance: "156 km",
    cargo: "Consumer Goods",
    weight: 5800,
    priority: "Normal",
  },
];

const maintenanceData = [
  {
    id: "M-441",
    maintenanceId: "MNT-441",
    vehicleId: "V-003",
    type: "Engine Overhaul",
    category: "Mechanical",
    priority: "High",
    cost: 85000,
    technician: "Alex Mutua",
    date: new Date("2025-01-12"),
    status: "In Progress",
    notes: "Cylinder head gasket replacement",
  },
  {
    id: "M-440",
    maintenanceId: "MNT-440",
    vehicleId: "V-001",
    type: "Tyre Replacement",
    category: "Tyres",
    priority: "Normal",
    cost: 42000,
    technician: "Ben Kipchoge",
    date: new Date("2025-01-18"),
    status: "Scheduled",
    notes: "All 6 rear tyres due for replacement",
  },
  {
    id: "M-439",
    maintenanceId: "MNT-439",
    vehicleId: "V-004",
    type: "Brake Service",
    category: "Brakes",
    priority: "High",
    cost: 28500,
    technician: "Alex Mutua",
    date: new Date("2025-01-08"),
    status: "Completed",
    notes: "Front and rear brake pad replacement",
  },
  {
    id: "M-438",
    maintenanceId: "MNT-438",
    vehicleId: "V-007",
    type: "Annual Inspection",
    category: "Inspection",
    priority: "Normal",
    cost: 15000,
    technician: "Chris Ouma",
    date: new Date("2024-12-20"),
    status: "Overdue",
    notes: "Vehicle due for government inspection",
  },
  {
    id: "M-437",
    maintenanceId: "MNT-437",
    vehicleId: "V-005",
    type: "Oil Change",
    category: "Servicing",
    priority: "Low",
    cost: 8500,
    technician: "Ben Kipchoge",
    date: new Date("2025-01-25"),
    status: "Scheduled",
    notes: "10,000 km interval service",
  },
];

async function main() {
  console.log("Seeding vehicles...");
  for (const vehicle of vehiclesData) {
    await prisma.vehicle.upsert({
      where: { regNumber: vehicle.regNumber },
      update: vehicle,
      create: vehicle,
    });
  }

  console.log("Seeding drivers...");
  for (const driver of driversData) {
    await prisma.driver.upsert({
      where: { licenseNumber: driver.licenseNumber },
      update: driver,
      create: driver,
    });
  }

  console.log("Seeding trips...");
  for (const trip of tripsData) {
    await prisma.trip.upsert({
      where: { tripId: trip.tripId },
      update: trip,
      create: trip,
    });
  }

  console.log("Seeding maintenance...");
  for (const mnt of maintenanceData) {
    await prisma.maintenance.upsert({
      where: { maintenanceId: mnt.maintenanceId },
      update: mnt,
      create: mnt,
    });
  }

  console.log("Database seeded successfully.");
}

main()
  .catch((e) => {
    console.error("Error during seeding:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
